package:
  name: busybox
  version: 1.36.1
  epoch: 0
  description: "swiss-army knife for embedded systems"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
  scriptlets:
    trigger:
      paths:
        - /bin
        - /sbin
        - /usr/bin
        - /usr/sbin
      script: |
        #!/bin/busybox sh
        /bin/busybox --install -s

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://distfiles.alpinelinux.org/distfiles/edge/busybox-1.35.0.tar.bz2
      expected-sha256: b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314
  - name: Configure
    runs: |
      cp busyboxconfig .config
  - runs: |
      make CC="${{host.triplet.gnu}}-gcc" V=1 -j$(nproc)
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/usr/sbin
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/tmp
      mkdir -p "${{targets.destdir}}"/var/cache/misc
      mkdir -p "${{targets.destdir}}"/bin
      mkdir -p "${{targets.destdir}}"/sbin
      mkdir -p "${{targets.destdir}}"/etc
      mkdir -p "${{targets.destdir}}"/usr/share/man/man1
      chmod 1777 "${{targets.destdir}}"/tmp
      install -m755 busybox "${{targets.destdir}}"/bin/busybox
      install -m644 securetty "${{targets.destdir}}"/etc/securetty
  - uses: strip
