package:
  name: file
  version: 5.45
  epoch: 0
  description: "file-type identification utility"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - file
pipeline:
  - uses: fetch
    with:
      uri: http://ftp.astron.com/pub/file/file-${{package.version}}.tar.gz
      expected-sha256: fc97f51029bb0e2c9f4e3bffefdaf678f0e039ee872b9de5c002a6d09c784d82
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
