package:
  name: file
  version: 5.42
  epoch: 1
  description: "file-type identification utility"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - file

pipeline:
  - uses: fetch
    with:
      uri: http://ftp.astron.com/pub/file/file-${{package.version}}.tar.gz
      expected-sha256: c076fb4d029c74073f15c43361ef572cfb868407d347190ba834af3b1639b0e4
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
