package:
  name: zlib
  version: 1.3
  epoch: 0
  description: "a library implementing the zlib compression algorithms"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MPL-2.0 AND MIT
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://zlib.net/zlib-${{package.version}}.tar.gz
      expected-sha256: ff0ba4c292013dbc27530b3a81e1f9a813cd39de01ca5e0f8bf355702efa593e
  - runs: |
      CHOST="${{host.triplet.gnu}}" ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --shared
  - uses: autoconf/make
  - runs: |
      make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.destdir}}"
  - uses: strip
